name: AutoRelease

on:
  push:
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release $version"
          tag: "$semver"
          draft: false
          regex: "/^Release #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}