name: Docker Image CI

on:
  push:
    branches: 
      - "main"
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Get app name
      id: get_app_name
      run: echo "::set-output name=app_name::$(({{ github.repository }} | cut -d "/" -f2 ))
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/%{{ steps.get_app_name.outputs.app_name }}:${{ github.ref_name }}
